//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaDrama_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KinoAndActor
    {
        public int IdKinoAndActor { get; set; }
        public int IdKino { get; set; }
        public Nullable<int> idActor { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual KinoAndSerial KinoAndSerial { get; set; }
    }
}
