//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaDrama_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KinoAndGroups
    {
        public int IdKinoAndGroups { get; set; }
        public int IdUsers { get; set; }
        public int IdKino { get; set; }
        public int IdGroups { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual KinoAndSerial KinoAndSerial { get; set; }
        public virtual Users Users { get; set; }
    }
}
