//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaDrama_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KinoAndGenre
    {
        public int IdKinoAndGenre { get; set; }
        public int idKino { get; set; }
        public int idGenre { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual KinoAndSerial KinoAndSerial { get; set; }
    }
}
